### ISSUE TITLE
Colliding with wall doesn't result in death

### ISSUE THREAD

**Issue by sector-f** [kirjavascript/snake-rs#3]
Upon "hitting" a wall, the snake simply wraps around to the other side. I am unsure if this is a bug or a feature, but it is worth pointing out that hitting the wall normally results in dying in Snake.

**Comment by kirjavascript** [comment]
Not colliding with a wall is behaviour taken from Snake II on the (canonical) Nokia 3310, but I wouldn't mind having this as something that could be toggled - preferably at runtime but compile time works too
